name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Print current directory
        run: |
          echo "Current directory:"
          pwd

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          pip install nbformat
          pip install nbconvert

      - name: Build AEPsych documentation
        run: |
          cd sphinx || exit
          make clean
          make html
          cd .. || exit
          cd website || exit
          yarn
          cd ..
          mkdir -p "website/pages/api/"
          cwd=$(pwd)
          python scripts/parse_sphinx.py -i "${cwd}/sphinx/build/html/" -o "${cwd}/website/pages/api/"
          SPHINX_JS_DIR='sphinx/build/html/_static/'
          DOCUSAURUS_JS_DIR='website/static/js/'
          mkdir -p $DOCUSAURUS_JS_DIR
          cp "${SPHINX_JS_DIR}documentation_options.js" "${DOCUSAURUS_JS_DIR}documentation_options.js"
          cp "${SPHINX_JS_DIR}jquery.js" "${DOCUSAURUS_JS_DIR}jquery.js"
          cp "${SPHINX_JS_DIR}underscore.js" "${DOCUSAURUS_JS_DIR}underscore.js"
          cp "${SPHINX_JS_DIR}doctools.js" "${DOCUSAURUS_JS_DIR}doctools.js"
          cp "${SPHINX_JS_DIR}language_data.js" "${DOCUSAURUS_JS_DIR}language_data.js"
          cp "${SPHINX_JS_DIR}searchtools.js" "${DOCUSAURUS_JS_DIR}searchtools.js"
          cp "sphinx/build/html/searchindex.js" "${DOCUSAURUS_JS_DIR}searchindex.js"
          cp -r "sphinx/build/html/_sources/" "website/static/_sphinx-sources/"
          mkdir -p "website/_tutorials"
          mkdir -p "website/static/files"
          python scripts/parse_tutorials.py -w "${cwd}"
          cd website || exit
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

      - name: Remove __pycache__ directories
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} \+
