name: Deploy Documentation to GitHub Pages

# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          pip install beautifulsoup4
          pip install nbformat
          pip install nbconvert
          pip install gpytorch
          pip install botorch>=0.1.3
          pip install jinja2
      - name: Build AEPsych documentation
        run: |
          ./scripts/build_docs.sh -b

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/aepsych
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
