# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
# https://github.com/marketplace/actions/github-pages
name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write
  deployments: write
  packages: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Node is required for npm
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -U sphinx
        pip install beautifulsoup4 ipython nbconvert "jinja2==3.0.3"
    - name: Dependencies
      run: |
        sudo apt-get install -y yarn
      id: build
    - name: Build the Website
      run: |
        ./scripts/build_docs.sh -b
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: website/build # The folder the action should deplo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: deploy-docusaurus-gh

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Check out repo
#         uses: actions/checkout@v2
#       # Node is required for npm
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v3.3.0
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           pip install -U sphinx
#           pip install beautifulsoup4 ipython nbconvert "jinja2==3.0.3"
#       - name: Build Docusaurus website
#         run: |
#           ./scripts/build_docs.sh -b
#         # run: |
#         #   cd website
#         #   npm install
#         #   npm run build
#       - name: Deploy to GitHub Pages
#         if: success()
#         uses: crazy-max/ghaction-github-pages@v2
#         with:
#           target_branch: gh-pages
#           build_dir: website/build
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
